name: Email new posts from The NYTimes Stone

on:
  rss:
    url: https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/the-stone/rss.xml

jobs:
  email:
    name: Send email
    runs-on: ubuntu-latest
    steps:
      - name: Fetch full content
        env:
          url: ${{on.rss.outputs.link}}
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          echo 'content<<EOF' >> $GITHUB_ENV
          curl "$url" | npx readability "$url" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{on.rss.outputs.title}}
          body: |
            ${{on.rss.outputs.link}}
            <br><br>
            ${{on.rss.outputs.content}}
            <br><br>
            ${{env.content}}
          to: sean.leather+feedflow@gmail.com
          from: NYTimes Stone <${{secrets.MAIL_USERNAME}}@gmail.com>
          content_type: text/html
