name: Email new posts from The Non Sequitur

on:
  rss:
    url: https://thenonsequitur.com/?feed=rss2

jobs:
  email:
    name: Send email
    runs-on: ubuntu-latest
    steps:
      - name: Install curl and readability
        run: |
          apt update && apt install -y curl
          npm install -g mozilla-readability-cli
      - name: Fetch full content
        env:
          url: ${{on.rss.outputs.link}}
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          curl "$url" | readability "$url"
      - name: Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{on.rss.outputs.title}}
          body: |
            ${{on.rss.outputs.link}}
            <br><br>
            ${{on.rss.outputs.content}}
          to: sean.leather+feedflow@gmail.com
          from: The Non Sequitur <${{secrets.MAIL_USERNAME}}@gmail.com>
          content_type: text/html
