name: Reset cache
on:
  workflow_dispatch:
jobs:
  reset:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionsflow clean
        uses: actionsflow/actionsflow-action@v1
        with:
          args: clean
          json-secrets: ${{ toJSON(secrets) }}
